# Generated by Django 4.0.10 on 2024-05-06 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=255, verbose_name='Единица измерения')),
                ('dateStart', models.DateField(blank=True, verbose_name='Дата начала')),
                ('dateEnd', models.DateField(blank=True, verbose_name='Дата окончания')),
                ('accepted', models.BooleanField(default=False, verbose_name='Принято')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.indicatorcategory', verbose_name='Категория')),
                ('subCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.indicatorsubcategory', verbose_name='Под категория')),
            ],
            options={
                'verbose_name': 'Индикатор',
                'verbose_name_plural': 'Индикаторы',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField(default=0, verbose_name='Приоритет')),
                ('image', models.TextField(blank=True, verbose_name='Ссылка на фото')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Медиа',
                'verbose_name_plural': 'Медиа',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('doc', 'Документ'), ('link', 'Ссылка')], default='link', max_length=25, verbose_name='Тип')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('link', models.TextField(blank=True, verbose_name='Ссылка')),
                ('datePublication', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.newscategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('type', models.CharField(blank=True, max_length=255, verbose_name='Тип')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.indicator', verbose_name='Индикатор')),
            ],
            options={
                'verbose_name': 'Мета данные',
                'verbose_name_plural': 'Мета данные',
            },
        ),
    ]
