# Generated by Django 4.0.10 on 2024-05-31 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_indicatorsubcategory_adddatadesc_and_more'),
        ('core', '0002_publication_usefullinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='graphCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.graphcategory', verbose_name='Категория графов'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='metadata',
            name='icon',
            field=models.TextField(blank=True, verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='metadata',
            name='subCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.indicatorsubcategory', verbose_name='Под категория'),
        ),
        migrations.AddField(
            model_name='metadata',
            name='value',
            field=models.FloatField(default=0, verbose_name='Значение'),
        ),
    ]
