# Generated by Django 4.0.10 on 2024-05-30 09:07

import category.imggenerate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='forSvg',
            field=models.FileField(blank=True, upload_to=category.imggenerate.all_image_path, verbose_name='Svg рисунок'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to=category.imggenerate.all_image_path, verbose_name='Рисунок'),
        ),
    ]
