# Generated by Django 4.0.10 on 2024-05-31 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_image_forsvg_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorsubcategory',
            name='addDataDesc',
            field=models.TextField(blank=True, verbose_name='Описание допалнительных данных'),
        ),
        migrations.AddField(
            model_name='indicatorsubcategory',
            name='additionalDataTitle',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок допалнительных данных'),
        ),
        migrations.CreateModel(
            name='GraphCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('value', models.FloatField(default=0, verbose_name='Значение')),
                ('subCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.indicatorsubcategory')),
            ],
            options={
                'verbose_name': 'Категория графов',
                'verbose_name_plural': 'Категории графов',
            },
        ),
    ]
